import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { ArrowRight, BadgeCheck, CheckCircle2, Clock3, HeartHandshake, MapPin, Phone, ShieldCheck, Star, Thermometer, Wrench, Zap } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { ContactOptions, QuoteBand, QuoteForm } from "@/components/site";
import { business, media, serviceAreas, services } from "@/lib/site-data";

export const Route=createFileRoute("/")({head:()=>({meta:[{title:"L Furnace Mechanicals | HVAC Repair & Installation in Indianapolis, IN"},{name:"description",content:"AC repair, furnace installation, and 24/7 emergency HVAC service across Indianapolis. Licensed & insured since 2010. Call (317) 506-3433."},{property:"og:title",content:"L Furnace Mechanicals"},{property:"og:description",content:"Heating & cooling done right. AC repair, furnace install, 24/7 emergency service in Indianapolis, IN."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:Home});

const trustBadges=[
  {icon:<ShieldCheck size={26}/>,title:"Licensed & Insured",text:"Full coverage on every job, every visit."},
  {icon:<HeartHandshake size={26}/>,title:"Satisfaction Guaranteed",text:"We don't leave until it's right."},
  {icon:<Clock3 size={26}/>,title:"24/7 Emergency Service",text:"Real humans answer, day or night."},
  {icon:<BadgeCheck size={26}/>,title:"Warranty on Every Job",text:"Parts and labor backed in writing."},
];

const whyChooseUs=[
  {icon:<ShieldCheck size={28}/>,title:"Licensed & Insured",text:"Certified technicians and full insurance on every job — your home is protected."},
  {icon:<Zap size={28}/>,title:"Upfront Flat-Rate Pricing",text:"You approve the price before we start. No surprises, no hourly creep."},
  {icon:<Clock3 size={28}/>,title:"Same-Day Service",text:"Most repairs finished the same day you call, with stocked trucks ready to go."},
  {icon:<Wrench size={28}/>,title:"15+ Years of Experience",text:"Serving Indianapolis since 2010 — we've seen (and fixed) it all."},
  {icon:<Thermometer size={28}/>,title:"100% Comfort Promise",text:"If your system isn't keeping you comfortable, we come back and make it right."},
];

const reviews=[
  {quote:"Our AC died during the July heat wave and Lamont had a tech out within two hours. Fixed the same afternoon, fair price, no upsell. These are our guys now.",name:"Marcus T.",area:"Indianapolis, IN"},
  {quote:"They replaced our 20-year-old furnace in a single day. The crew was clean, explained everything, and our heating bill dropped noticeably that winter.",name:"Dana W.",area:"Fishers, IN"},
  {quote:"Called at 11pm with no heat in January — someone actually answered and we had heat by morning. You can't put a price on that kind of reliability.",name:"Priya S.",area:"Carmel, IN"},
];

const faqs=[
  {q:"Do you offer 24/7 emergency HVAC service?",a:"Yes. Heating and cooling emergencies don't wait for business hours, and neither do we. Call (317) 506-3433 any time — a real technician answers, and most emergency calls get same-day service across the Indianapolis area."},
  {q:"How often should I have my HVAC system serviced?",a:"Twice a year: a cooling tune-up in spring and a heating tune-up in fall. Regular maintenance catches small issues before they become breakdowns, keeps your warranty valid, and can cut energy bills by up to 15%."},
  {q:"Should I repair or replace my air conditioner?",a:"As a rule of thumb: if your system is over 12–15 years old, needs frequent repairs, or a single repair costs more than half the price of a new unit, replacement is the smarter investment. We'll always give you an honest assessment — and we'll tell you when a repair is all you need."},
  {q:"What brands do you service and install?",a:"We service all major brands — Carrier, Trane, Lennox, Goodman, Rheem, York, and more. For installations, we'll recommend the right-sized, high-efficiency system for your home and budget, not just the most expensive option."},
  {q:"Do you warranty your work?",a:"Every job is backed in writing: manufacturer warranties on equipment plus our own workmanship warranty on labor. If something we installed isn't right, we come back and fix it at no charge."},
];

function Home(){return <>
{/* HERO — Ken Burns real-photo background + quote form */}
<section id="home" className="relative isolate scroll-mt-28 overflow-hidden bg-forest"><div className="absolute inset-0 -z-20 overflow-hidden"><img src={media.heroPoster} alt="HVAC technician servicing an air conditioning unit" className="hero-kenburns h-full w-full object-cover"/></div><div className="absolute inset-0 -z-10 bg-gradient-to-r from-forest via-forest/80 to-forest/20"/><div className="page-shell grid min-h-[calc(100svh-106px)] items-center gap-10 py-10 md:py-24 lg:grid-cols-[minmax(0,1fr)_400px]"><div className="max-w-3xl text-primary-foreground"><p className="mb-4 inline-flex items-center gap-2 rounded-full bg-primary/15 px-4 py-1.5 text-xs font-extrabold uppercase tracking-[.14em] text-leaf"><Star size={13} fill="currentColor"/> {business.rating} rated on Google</p><h1 className="text-balance text-4xl font-extrabold leading-[.94] sm:text-7xl lg:text-8xl">Comfort you can count on, all year round.</h1><p className="mt-6 max-w-xl text-base leading-7 opacity-90 sm:text-lg">From AC repair to full furnace installs, {business.name} keeps Indianapolis homes comfortable — honest pricing, clean work, and 24/7 emergency service.</p><div className="mt-8"><ContactOptions/></div></div><div className="w-full max-w-md justify-self-center lg:justify-self-end"><QuoteForm/></div></div></section>

{/* TRUST BADGES */}
<section className="border-b bg-background"><div className="page-shell grid grid-cols-2 gap-6 py-8 lg:grid-cols-4">{trustBadges.map(b=><div key={b.title} className="flex items-start gap-3"><span className="grid size-11 shrink-0 place-items-center rounded-full bg-secondary text-earth">{b.icon}</span><div><strong className="block text-sm font-extrabold">{b.title}</strong><span className="mt-1 block text-xs leading-5 text-muted-foreground">{b.text}</span></div></div>)}</div></section>

{/* ABOUT */}
<section id="about" className="section-space scroll-mt-24"><div className="page-shell grid gap-12 lg:grid-cols-2 lg:items-center"><div className="relative"><img src={media.about} alt="L Furnace Mechanicals technician in front of an installed air conditioner" loading="lazy" className="aspect-[4/5] w-full rounded-lg object-cover"/><div className="absolute -bottom-5 right-0 rounded-lg bg-primary p-6 text-primary-foreground shadow-xl"><strong className="font-display text-4xl">15+</strong><span className="block text-xs font-bold">years serving Indianapolis</span></div></div><div><p className="eyebrow">About us</p><h2 className="mt-3 text-4xl font-extrabold sm:text-5xl">Indianapolis trusts us with their comfort.</h2><p className="mt-5 leading-7 text-muted-foreground">Since 2010, owner {business.owner} and the {business.name} team have kept homes across Indianapolis warm in winter and cool in summer. We're the crew neighbors recommend — straightforward advice, fair flat-rate pricing, and work we're proud to sign our name to.</p><ul className="mt-6 grid gap-3">{["Background-checked, certified technicians","Shoe covers and drop cloths on every visit","We explain the fix before we bill for it","Locally owned — your money stays in Indianapolis"].map(point=><li key={point} className="flex items-start gap-2.5 text-sm font-bold"><CheckCircle2 size={18} className="mt-0.5 shrink-0 text-earth"/>{point}</li>)}</ul><div className="mt-8"><ContactOptions/></div></div></div></section>

{/* SERVICES */}
<section id="services" className="section-space scroll-mt-24 bg-surface"><div className="page-shell"><div className="grid gap-8 md:grid-cols-[1fr_.8fr]"><div><p className="eyebrow">What we do</p><h2 className="mt-3 text-balance text-4xl font-extrabold sm:text-5xl">Heating & cooling, handled end to end.</h2></div><p className="self-end leading-7 text-muted-foreground">One team for repairs, replacements, and new installs — so you never have to chase down a different contractor for each job.</p></div><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{services.map((s,i)=><article key={s.title} className="group overflow-hidden rounded-lg border bg-card shadow-sm"><div className="aspect-[4/3] overflow-hidden"><img src={s.image} alt={s.title} loading="lazy" className="h-full w-full object-cover transition duration-500 group-hover:scale-105"/></div><div className="p-6"><span className="text-xs font-extrabold text-earth">0{i+1}</span><h3 className="mt-2 text-2xl font-bold">{s.title}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{s.description}</p><a href="#contact" className="mt-5 inline-flex items-center gap-2 font-extrabold text-primary">Ask about this service <ArrowRight size={17}/></a></div></article>)}</div></div></section>

{/* WHY CHOOSE US */}
<section className="section-space"><div className="page-shell"><p className="eyebrow text-center">Why choose us</p><h2 className="mx-auto mt-3 max-w-2xl text-center text-4xl font-extrabold sm:text-5xl">The HVAC company Indianapolis recommends.</h2><div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-5">{whyChooseUs.map(f=><div key={f.title} className="rounded-lg border bg-card p-6 shadow-sm transition-transform hover:-translate-y-1"><span className="grid size-12 place-items-center rounded-full bg-secondary text-earth">{f.icon}</span><h3 className="mt-4 text-lg font-extrabold">{f.title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{f.text}</p></div>)}</div></div></section>

{/* SERVICE AREAS */}
<section id="service-areas" className="section-space scroll-mt-24 bg-forest text-primary-foreground"><div className="page-shell grid gap-10 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><div><p className="eyebrow !text-leaf">Service areas</p><h2 className="mt-3 text-4xl font-extrabold sm:text-5xl">Proudly serving greater Indianapolis.</h2><p className="mt-5 max-w-xl leading-7 opacity-80">From downtown to the suburbs, our technicians are never far away. Don't see your town? Call us — if you're nearby, we'll make it work.</p><a href={business.phoneHref} className="button-primary mt-7"><Phone size={18}/> Call {business.phone}</a></div><div className="flex flex-wrap gap-3">{serviceAreas.map(area=><span key={area} className="inline-flex items-center gap-1.5 rounded-full border border-primary-foreground/20 bg-primary-foreground/10 px-4 py-2.5 text-sm font-bold"><MapPin size={14} className="text-leaf"/>{area}</span>)}</div></div></section>

{/* REVIEWS */}
<section id="reviews" className="section-space scroll-mt-24"><div className="page-shell"><p className="eyebrow text-center">Reviews</p><h2 className="mt-3 text-center text-4xl font-extrabold sm:text-5xl">{business.rating} on Google — from your neighbors.</h2><div className="mt-10 grid gap-5 md:grid-cols-3">{reviews.map(r=><figure key={r.name} className="rounded-lg border-t-4 border-primary bg-card p-7 shadow-sm"><div className="flex gap-1 text-earth">{[1,2,3,4,5].map(x=><Star key={x} size={16} fill="currentColor"/>)}</div><blockquote className="mt-6 leading-7">“{r.quote}”</blockquote><figcaption className="mt-5 text-sm font-extrabold">{r.name} <span className="font-normal text-muted-foreground">· {r.area}</span></figcaption></figure>)}</div></div></section>

{/* FAQ */}
<section id="faq" className="section-space scroll-mt-24 bg-surface"><div className="page-shell max-w-3xl"><p className="eyebrow text-center">FAQ</p><h2 className="mt-3 text-center text-4xl font-extrabold sm:text-5xl">Questions, answered.</h2><Accordion type="single" collapsible className="mt-10 rounded-lg border bg-card px-6 shadow-sm">{faqs.map((f,i)=><AccordionItem key={f.q} value={`item-${i}`}><AccordionTrigger className="py-5 text-left text-base font-extrabold hover:no-underline">{f.q}</AccordionTrigger><AccordionContent className="pb-5 leading-7 text-muted-foreground">{f.a}</AccordionContent></AccordionItem>)}</Accordion></div></section>

<QuoteBand/>
<ContactSection/>
</>}

const selectClass="min-h-12 rounded-md border bg-background px-3 text-base text-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring";

function ContactSection(){const[sent,setSent]=useState(false);return <section id="contact" className="section-space scroll-mt-24"><div className="page-shell">{sent?<div className="mx-auto max-w-xl text-center"><CheckCircle2 className="mx-auto text-earth" size={52}/><h2 className="mt-5 text-4xl font-extrabold">Thanks — we’ve got your request.</h2><p className="mt-4 leading-7 text-muted-foreground">We’ll review the details and follow up shortly. For a quicker conversation, you can also call us.</p><a href={business.phoneHref} className="button-primary mt-7"><Phone size={18}/> Call Now</a></div>:<div className="grid gap-12 lg:grid-cols-[1.15fr_.85fr]"><form onSubmit={e=>{e.preventDefault();setSent(true)}} className="rounded-lg border bg-card p-6 shadow-sm sm:p-9"><p className="eyebrow">Free estimate</p><h2 className="mt-3 text-4xl font-extrabold">Get your free quote today.</h2><div className="mt-8 grid gap-5 sm:grid-cols-2"><Field label="Name" name="name" type="text"/><Field label="Phone" name="phone" type="tel"/><Field label="Email" name="email" type="email"/><label className="grid gap-2 text-sm font-bold">Service<select required name="service" className={selectClass}><option value="">Choose a service</option>{services.map(s=><option key={s.title}>{s.title}</option>)}<option>Something else</option></select></label></div><label className="mt-5 grid gap-2 text-sm font-bold">Tell us what's going on<textarea required minLength={10} maxLength={1000} name="message" rows={6} className="rounded-md border bg-background p-3 font-normal" placeholder="AC blowing warm air? Furnace making noise? Tell us the symptoms..."/></label><label className="mt-5 flex items-start gap-3 text-xs leading-5 text-muted-foreground"><input required type="checkbox" className="mt-1 accent-primary"/>I agree to be contacted about this quote request.</label><Button type="submit" size="lg" className="mt-6 w-full font-extrabold">Request my free quote</Button></form><div><p className="eyebrow">Talk to us</p><h2 className="mt-3 text-4xl font-extrabold">A friendly first conversation.</h2><div className="mt-8 grid gap-4"><ContactLine icon={<Phone/>} title="Phone" text={business.phone}/><ContactLine icon={<MapPin/>} title="Address" text={business.address}/></div><a href={business.phoneHref} className="button-primary mt-7"><Phone size={18}/> Call Now</a><div className="mt-8 overflow-hidden rounded-lg border bg-muted"><iframe title="L Furnace Mechanicals map" src="https://www.google.com/maps?q=Indianapolis%2C%20IN%2046268&output=embed" className="h-72 w-full" loading="lazy" referrerPolicy="no-referrer-when-downgrade"/></div></div></div>}</div></section>}

function Field({label,name,type}:{label:string;name:string;type:string}){return <label className="grid gap-2 text-sm font-bold">{label}<input required name={name} type={type} maxLength={type==="email"?255:100} className="min-h-12 rounded-md border bg-background px-3 font-normal"/></label>}
function ContactLine({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <div className="grid grid-cols-[auto_1fr] gap-4 border-b pb-4"><span className="text-earth">{icon}</span><div><strong className="block">{title}</strong><span className="text-sm text-muted-foreground">{text}</span></div></div>}
