import { ArrowRight, CheckCircle2, Clock3, Flame, Mail, MapPin, Menu, Phone, X } from "lucide-react";
import { useState, type ReactNode } from "react";
import { business, hours, nav, services } from "@/lib/site-data";

export function Header() {
  const [open,setOpen]=useState(false);
  return <><div className="bg-forest text-primary-foreground"><div className="page-shell flex items-center justify-between gap-4 py-2 text-xs font-bold">
    <div className="flex min-w-0 items-center gap-5">
      <a href={`mailto:${business.email}`} className="hidden items-center gap-1.5 opacity-80 hover:opacity-100 sm:flex"><Mail size={13}/>{business.email}</a>
      <span className="hidden items-center gap-1.5 opacity-80 md:flex"><MapPin size={13}/>{business.address}</span>
    </div>
    <a href="#contact" className="shrink-0 rounded-full bg-primary px-4 py-1.5 font-extrabold text-primary-foreground transition-colors hover:bg-earth">Book Now</a>
  </div></div>
  <header className="sticky top-0 z-50 border-b bg-background/95 backdrop-blur"><div className="page-shell grid min-h-18 grid-cols-[minmax(0,1fr)_auto] items-center gap-3">
    <a href="#home" className="flex min-w-0 items-center gap-2"><span className="grid size-9 shrink-0 place-items-center rounded-full bg-primary text-primary-foreground"><Flame size={18}/></span><span className="truncate font-display text-lg font-extrabold">L Furnace <span className="text-earth">Mechanicals</span></span></a>
    <nav className="hidden items-center gap-6 lg:flex">{nav.map(i=><a key={i.to} href={i.to} className="text-sm font-bold text-muted-foreground transition-colors hover:text-primary">{i.label}</a>)}<a href={business.phoneHref} className="flex items-center gap-2 rounded-full bg-forest px-4 py-2.5 text-sm font-extrabold text-primary-foreground transition-colors hover:bg-moss"><Phone size={16}/>{business.phone}</a></nav>
    <button aria-label={open?"Close menu":"Open menu"} onClick={()=>setOpen(!open)} className="grid size-12 place-items-center rounded-md border lg:hidden">{open?<X/>:<Menu/>}</button>
  </div></header>{open&&<div className="fixed inset-0 z-[60] lg:hidden"><div className="absolute inset-0 bg-foreground/60" onClick={()=>setOpen(false)} aria-hidden="true"/><nav className="drawer-panel absolute right-0 top-0 flex h-full w-[85%] max-w-sm flex-col overflow-y-auto bg-background p-6 shadow-2xl"><div className="flex items-center justify-between"><span className="font-display text-lg font-extrabold">Menu</span><button aria-label="Close menu" onClick={()=>setOpen(false)} className="grid size-12 place-items-center rounded-md border"><X/></button></div><div className="mt-6 grid gap-1">{nav.map(i=><a key={i.to} href={i.to} onClick={()=>setOpen(false)} className="block rounded-md px-3 py-3.5 font-bold hover:bg-muted">{i.label}</a>)}</div><div className="mt-auto grid gap-3 pt-6"><a href={business.phoneHref} onClick={()=>setOpen(false)} className="button-primary w-full"><Phone size={16}/> Call {business.phone}</a><a href="#contact" onClick={()=>setOpen(false)} className="button-primary w-full">Get a free quote</a></div></nav></div>}</>;
}

export function Footer(){return <footer className="bg-forest text-primary-foreground"><div className="page-shell grid gap-10 py-10 sm:grid-cols-2 md:py-14 lg:grid-cols-[1.2fr_.7fr_.8fr_1fr]">
  <div><div className="flex items-center gap-2 font-display text-xl font-extrabold"><span className="grid size-9 place-items-center rounded-full bg-primary text-primary-foreground"><Flame size={18}/></span> L Furnace Mechanicals</div><p className="mt-4 max-w-sm text-sm leading-7 opacity-75">Heating and cooling done right since 2010. Honest pricing, clean work, and comfort you can count on across Indianapolis.</p><a href={business.phoneHref} className="mt-5 inline-flex items-center gap-2 font-extrabold text-leaf"><Phone size={16}/>{business.phone}</a></div>
  <div><h3 className="font-bold">Quick Links</h3><div className="mt-4 grid gap-2">{nav.map(i=><a key={i.to} href={i.to} className="text-sm opacity-75 hover:opacity-100">{i.label}</a>)}</div></div>
  <div><h3 className="font-bold">Services</h3><div className="mt-4 grid gap-2">{services.map(s=><a key={s.title} href="#services" className="text-sm opacity-75 hover:opacity-100">{s.title}</a>)}</div></div>
  <div><h3 className="font-bold">Contact</h3><div className="mt-4 grid gap-3 text-sm opacity-75"><span className="flex items-start gap-2"><MapPin size={15} className="mt-0.5 shrink-0"/>{business.address}</span><a href={`mailto:${business.email}`} className="flex items-start gap-2 hover:opacity-100"><Mail size={15} className="mt-0.5 shrink-0"/>{business.email}</a></div><h3 className="mt-6 font-bold">Hours</h3><div className="mt-3 grid gap-1.5 text-sm opacity-75">{hours.map(h=><div key={h.days} className="flex justify-between gap-3"><span>{h.days}</span><span className="text-right">{h.time}</span></div>)}</div></div>
</div><div className="border-t border-primary-foreground/15 py-5"><div className="page-shell flex flex-col gap-2 text-xs opacity-60 sm:flex-row sm:justify-between"><span>© 2026 L Furnace Mechanicals. All rights reserved.</span><span>Indianapolis, IN · Since 2010</span></div></div></footer>}

export function PageHero({eyebrow,title,copy,image}:{eyebrow:string;title:string;copy:string;image:string}){return <section className="relative isolate min-h-[460px] overflow-hidden bg-forest"><img src={image} alt="" className="absolute inset-0 -z-20 h-full w-full object-cover"/><div className="absolute inset-0 -z-10 bg-forest/70"/><div className="page-shell flex min-h-[460px] items-end py-16"><div className="max-w-3xl text-primary-foreground"><p className="mb-4 text-xs font-extrabold uppercase tracking-[.16em] text-leaf">{eyebrow}</p><h1 className="text-balance text-5xl font-extrabold leading-[.98] sm:text-7xl">{title}</h1><p className="mt-6 max-w-2xl text-base leading-7 opacity-85 sm:text-lg">{copy}</p></div></div></section>}

export function QuoteBand(){return <section className="relative isolate overflow-hidden bg-forest py-14 text-primary-foreground md:py-20"><img src="/images/cta-band.jpg" alt="" loading="lazy" className="absolute inset-0 -z-20 h-full w-full object-cover"/><div className="absolute inset-0 -z-10 bg-forest/80"/><div className="page-shell flex flex-col items-start justify-between gap-8 md:flex-row md:items-center"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[.15em] text-leaf">24/7 emergency service</p><h2 className="mt-3 text-3xl font-extrabold sm:text-4xl">No heat? No cool? Call now — we answer.</h2><p className="mt-3 leading-7 opacity-80">Day or night, a real technician picks up. Most emergency calls get same-day service across Indianapolis.</p></div><a href={business.phoneHref} className="button-primary shrink-0 text-lg"><Phone size={20}/> Call {business.phone}</a></div></section>}

export function ContactOptions(){return <div className="flex flex-wrap gap-3"><a href="#contact" className="button-primary">Get a free quote <ArrowRight size={17}/></a><a href={business.phoneHref} className="inline-flex min-h-12 items-center gap-2 rounded-md border border-current px-5 font-extrabold"><Phone size={17}/> Call Now</a></div>}

export function IconStat({icon,number,label}:{icon:ReactNode;number:string;label:string}){return <div className="border-l-2 border-accent pl-5"><div className="text-earth">{icon}</div><strong className="mt-4 block font-display text-3xl">{number}</strong><span className="text-sm text-muted-foreground">{label}</span></div>}

const inputClass="w-full min-h-12 rounded-lg border-0 bg-white px-4 py-3 text-base text-foreground placeholder:text-muted-foreground/60 focus:outline-none focus:ring-2 focus:ring-accent";
export function QuoteForm(){const[sent,setSent]=useState(false);if(sent)return <div className="w-full rounded-2xl bg-forest p-8 text-primary-foreground shadow-xl"><div className="flex min-h-[380px] flex-col items-center justify-center gap-4 text-center"><CheckCircle2 className="size-14 text-leaf"/><h3 className="font-display text-2xl font-extrabold">Thanks!</h3><p className="opacity-80">We’ll be in touch shortly.</p></div></div>;return <div className="w-full rounded-2xl bg-forest p-8 text-primary-foreground shadow-xl"><h3 className="text-center font-display text-lg font-extrabold uppercase tracking-wide">Get a Free Quote</h3><form className="mt-6 space-y-4" onSubmit={e=>{e.preventDefault();setSent(true);}}><div><label className="mb-1.5 block text-sm font-bold">Full Name *</label><input required type="text" autoComplete="name" placeholder="John Smith" className={inputClass}/></div><div><label className="mb-1.5 block text-sm font-bold">Phone *</label><input required type="tel" inputMode="tel" autoComplete="tel" placeholder="Example: (317) 555-1234" className={inputClass}/></div><div><label className="mb-1.5 block text-sm font-bold">Address *</label><input required type="text" autoComplete="street-address" placeholder="Street address, City, ZIP" className={inputClass}/></div><div><label className="mb-1.5 block text-sm font-bold">Service Type *</label><select required defaultValue="" className={inputClass}><option value="" disabled>Choose a service</option>{services.map(s=><option key={s.title}>{s.title}</option>)}<option>Something else</option></select></div><div><label className="mb-1.5 block text-sm font-bold">Message</label><textarea rows={3} placeholder="Tell us what's going on..." className={`${inputClass} resize-none`}/></div><button type="submit" className="button-primary w-full rounded-full py-4 text-base uppercase tracking-wide">Send</button><p className="flex items-center justify-center gap-1.5 text-xs opacity-70"><Clock3 size={13}/> Average response time: under 30 minutes</p></form></div>}

export function MobileCallBar(){return <><div aria-hidden="true" className="h-16 md:hidden"/><a href={business.phoneHref} className="fixed inset-x-0 bottom-0 z-50 flex min-h-16 items-center justify-center gap-2 bg-forest px-4 py-4 text-base font-extrabold text-primary-foreground shadow-[0_-4px_20px_rgba(0,0,0,0.25)] md:hidden"><Phone size={18}/> Call Now · {business.phone}</a></>}
